# Generated by Django 4.2.8 on 2024-11-07 07:21

from django.db import migrations, transaction


def forwards(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Version = apps.get_model("djangocms_versioning", "Version")
    VersionLock = apps.get_model("djangocms_version_locking", "VersionLock")

    version_lock_qs = VersionLock.objects.using(db_alias).all()
    versions = set(Version.objects.using(db_alias).filter(pk__in=version_lock_qs.values('version')))

    with transaction.atomic():
        for version in versions:
            version.locked_by = version.versionlock.created_by

    Version.objects.using(db_alias).bulk_update(versions, ['locked_by']) 


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_version_locking', '0001_initial'),
        ('djangocms_versioning', '0017_merge_20230514_1027'),
    ]

    operations = [
        migrations.RunPython(forwards, reverse_code=migrations.RunPython.noop)
    ]
