# Generated by Django 4.2.16 on 2024-11-07 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_version_locking', '0002_migrate_locked_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VersionLock',
        ),
    ]
